name: Build and Publish

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.22'

      - name: Build and Test on Linux
        run: |
          go build -ldflags "-s -w" -o fidus

      - name: Upload Linux Binary
        uses: actions/upload-artifact@v2
        with:
          name: fidus-linux
          path: fidus

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          files: "fidus"

  build_windows:
    runs-on: windows-latest
    permissions:
      contents: write 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.22'

      - name: Build and Test on Windows
        run: |
          go build -ldflags "-s -w" -o fidus.exe

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          files: "fidus.exe"

